-- MySQL Script generated by MySQL Workbench
-- Thu Jan 23 21:08:56 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Plane_Types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Plane_Types` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Plane_Types` (
  `id` BIGINT(32) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Countries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Countries` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Countries` (
  `id` BIGINT(32) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  `code` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `code_UNIQUE` (`code` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Addresses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Addresses` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Addresses` (
  `id` BIGINT(32) UNSIGNED NOT NULL AUTO_INCREMENT,
  `city` VARCHAR(20) NOT NULL,
  `post_code` VARCHAR(10) NOT NULL,
  `street` VARCHAR(25) NOT NULL,
  `street_number` VARBINARY(5) NULL,
  `apartment_number` VARCHAR(5) NULL,
  `country_id` BIGINT(32) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Addresses_Countries1_idx` (`country_id` ASC) VISIBLE,
  CONSTRAINT `fk_Addresses_Countries1`
    FOREIGN KEY (`country_id`)
    REFERENCES `mydb`.`Countries` (`id`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Airports`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Airports` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Airports` (
  `id` BIGINT(32) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `code` VARCHAR(45) NULL,
  `address_id` BIGINT(32) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  INDEX `fk_Airports_Addresses1_idx` (`address_id` ASC) VISIBLE,
  CONSTRAINT `fk_Airports_Addresses1`
    FOREIGN KEY (`address_id`)
    REFERENCES `mydb`.`Addresses` (`id`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Hangars`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Hangars` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Hangars` (
  `id` BIGINT(32) NOT NULL,
  `name` VARCHAR(20) NOT NULL,
  `capacity` INT NOT NULL,
  `airport_id` BIGINT(32) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Hangars_Airports1_idx` (`airport_id` ASC) VISIBLE,
  CONSTRAINT `fk_Hangars_Airports1`
    FOREIGN KEY (`airport_id`)
    REFERENCES `mydb`.`Airports` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Airlines`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Airlines` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Airlines` (
  `id` BIGINT(32) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `registration_country_id` BIGINT(32) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Airlines_Countries1_idx` (`registration_country_id` ASC) VISIBLE,
  CONSTRAINT `fk_Airlines_Countries1`
    FOREIGN KEY (`registration_country_id`)
    REFERENCES `mydb`.`Countries` (`id`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Planes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Planes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Planes` (
  `id` BIGINT(32) UNSIGNED NOT NULL AUTO_INCREMENT,
  `registration` VARCHAR(10) NULL,
  `number_of_seats` INT(4) NOT NULL,
  `production_year` YEAR(4) NOT NULL,
  `plane_type_id` BIGINT(32) UNSIGNED NOT NULL,
  `hangar_id` BIGINT(32) NULL,
  `airlane_id` BIGINT(32) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `registration_UNIQUE` (`registration` ASC) VISIBLE,
  INDEX `fk_Planes_Plane_Types_idx` (`plane_type_id` ASC) VISIBLE,
  INDEX `fk_Planes_Hangars1_idx` (`hangar_id` ASC) VISIBLE,
  INDEX `fk_Planes_Airlines1_idx` (`airlane_id` ASC) VISIBLE,
  CONSTRAINT `fk_Planes_Plane_Types`
    FOREIGN KEY (`plane_type_id`)
    REFERENCES `mydb`.`Plane_Types` (`id`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Planes_Hangars1`
    FOREIGN KEY (`hangar_id`)
    REFERENCES `mydb`.`Hangars` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Planes_Airlines1`
    FOREIGN KEY (`airlane_id`)
    REFERENCES `mydb`.`Airlines` (`id`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`People`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`People` ;

CREATE TABLE IF NOT EXISTS `mydb`.`People` (
  `id` BIGINT(32) UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(15) NOT NULL,
  `second_name` VARCHAR(15) NULL,
  `last_name` VARCHAR(25) NOT NULL,
  `address_id` BIGINT(32) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_People_Addresses1_idx` (`address_id` ASC) VISIBLE,
  CONSTRAINT `fk_People_Addresses1`
    FOREIGN KEY (`address_id`)
    REFERENCES `mydb`.`Addresses` (`id`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Flying_Licences`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Flying_Licences` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Flying_Licences` (
  `id` BIGINT(32) NOT NULL,
  `licence_code` VARCHAR(20) NOT NULL,
  `issue_date` DATE NOT NULL,
  `expiration_date` DATE NOT NULL,
  `pilot_id` BIGINT(32) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `number_UNIQUE` (`licence_code` ASC) VISIBLE,
  INDEX `fk_Flying_Licences_People1_idx` (`pilot_id` ASC) VISIBLE,
  CONSTRAINT `fk_Flying_Licences_People1`
    FOREIGN KEY (`pilot_id`)
    REFERENCES `mydb`.`People` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Flights`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Flights` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Flights` (
  `id` BIGINT(32) UNSIGNED NOT NULL AUTO_INCREMENT,
  `start_time` DATETIME NOT NULL,
  `landing_time` DATETIME NOT NULL,
  `plane_id` BIGINT(32) UNSIGNED NOT NULL,
  `start_airport_id` BIGINT(32) UNSIGNED NOT NULL,
  `destination_airport_id` BIGINT(32) UNSIGNED NOT NULL,
  `first_pilot_id` BIGINT(32) UNSIGNED NULL,
  `second_pilot_id` BIGINT(32) UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Flights_Planes1_idx` (`plane_id` ASC) VISIBLE,
  INDEX `fk_Flights_Airports1_idx` (`start_airport_id` ASC) VISIBLE,
  INDEX `fk_Flights_Airports2_idx` (`destination_airport_id` ASC) VISIBLE,
  INDEX `fk_Flights_People1_idx` (`first_pilot_id` ASC) VISIBLE,
  INDEX `fk_Flights_People2_idx` (`second_pilot_id` ASC) VISIBLE,
  CONSTRAINT `fk_Flights_Planes1`
    FOREIGN KEY (`plane_id`)
    REFERENCES `mydb`.`Planes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Flights_Airports1`
    FOREIGN KEY (`start_airport_id`)
    REFERENCES `mydb`.`Airports` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Flights_Airports2`
    FOREIGN KEY (`destination_airport_id`)
    REFERENCES `mydb`.`Airports` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Flights_People1`
    FOREIGN KEY (`first_pilot_id`)
    REFERENCES `mydb`.`People` (`id`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Flights_People2`
    FOREIGN KEY (`second_pilot_id`)
    REFERENCES `mydb`.`People` (`id`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ticket_Classes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Ticket_Classes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Ticket_Classes` (
  `id` BIGINT(36) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tickets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Tickets` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Tickets` (
  `id` BIGINT(32) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ticket_code` VARCHAR(10) NOT NULL,
  `seat` VARCHAR(5) NOT NULL,
  `flight_id` BIGINT(32) UNSIGNED NOT NULL,
  `passenger_id` BIGINT(32) UNSIGNED NOT NULL,
  `ticket_class_id` BIGINT(36) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `number_UNIQUE` (`ticket_code` ASC) VISIBLE,
  INDEX `fk_Tickets_Flights1_idx` (`flight_id` ASC) VISIBLE,
  INDEX `fk_Tickets_People1_idx` (`passenger_id` ASC) VISIBLE,
  INDEX `fk_Tickets_Ticket_Classes1_idx` (`ticket_class_id` ASC) VISIBLE,
  CONSTRAINT `fk_Tickets_Flights1`
    FOREIGN KEY (`flight_id`)
    REFERENCES `mydb`.`Flights` (`id`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tickets_People1`
    FOREIGN KEY (`passenger_id`)
    REFERENCES `mydb`.`People` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tickets_Ticket_Classes1`
    FOREIGN KEY (`ticket_class_id`)
    REFERENCES `mydb`.`Ticket_Classes` (`id`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
